### ISSUE TITLE
ES6 Promise

### ISSUE THREAD

**Issue by garymcm** [taniarascia/es6#1]
I hope this is not a nitpick, but for the ES6 Promise example, calling ```resolve(doSecond)``` inside the Promise is unnecessary and has the effect of returning the concrete arrow function to ```then()```. For example:
```
...

doFirst.then( x => x() ); 

"Do first."
"Do second."
```
Since your ```doSecond``` accepts no parameters it still works though. I think for clarity, it's better to simply call ```resolve()```?

**Comment by taniarascia** [comment]
Not a nitpick at all! I'm happy for the help. Would you like to submit a PR, or should I just change it?

**Comment by garymcm** [comment]
Sorry I am still a noob at this (github). Yes, I would be glad to do a PR!

**Comment by taniarascia** [comment]
Well,  I'll just go ahead and fix it. Thanks!
